version: '3.7'

services:
  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      # - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  # backend:
  #   build: ./backend
  #   ports:
  #     - 8080:8080